{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d7789b7d-02a7-40ce-bee6-42784b7078ff",
   "metadata": {},
   "outputs": [],
   "source": [
    "import difflib\n",
    "import os\n",
    "import sys\n",
    "\n",
    "# Safely attempt to import pandas\n",
    "try:\n",
    "    import pandas as pd\n",
    "except ImportError:\n",
    "    print(\"CRITICAL: The pandas library is required to run this script.\")\n",
    "    print(\"Please install it by running: pip install pandas openpyxl\")\n",
    "    input(\"\\nPress Enter to exit...\")\n",
    "    sys.exit()\n",
    "\n",
    "file_name = \"ExampleFootball.xlsx\"\n",
    "\n",
    "try:\n",
    "    if not os.path.exists(file_name):\n",
    "        print(f\"Notification: The file {file_name} was not found.\")\n",
    "        print(\"Please place this script in the same folder as your Excel file.\")\n",
    "        df = None\n",
    "    else:\n",
    "        df = pd.read_excel(file_name)\n",
    "except Exception:\n",
    "    print(\"Notification: Could not read the file. Please check if it is open in Excel or corrupted.\")\n",
    "    df = None\n",
    "\n",
    "# Proceed only if the data frame loaded correctly\n",
    "if df is not None:\n",
    "    try:\n",
    "        # Automatically find the player/name column dynamically\n",
    "        player_col = None\n",
    "        for col in df.columns:\n",
    "            if \"player\" in str(col).lower() or \"name\" in str(col).lower():\n",
    "                player_col = col\n",
    "                break\n",
    "        \n",
    "        if player_col is None and len(df.columns) > 0:\n",
    "            player_col = df.columns[0]\n",
    "\n",
    "        if player_col is not None:\n",
    "            # Force conversion to safe string values\n",
    "            df[player_col] = df[player_col].astype(str)\n",
    "\n",
    "            print(\"\\n┌────────────────────────────────────┐\")\n",
    "            print(\"│ The League Tables Football Finder  │\")\n",
    "            print(\"└────────────────────────────────────┘\")\n",
    "            print(\"*(Type 'exit' at any time to close)*\")\n",
    "            print(\"*(Separate multiple players with commas, e.g., Messi, Ronaldo)*\")\n",
    "\n",
    "            # Continuous loop\n",
    "            while True:\n",
    "                user_input = input(\"\\nEnter player name(s): \").strip()\n",
    "                \n",
    "                if user_input.lower() == \"exit\":\n",
    "                    print(\"\\nExiting program. Goodbye!\")\n",
    "                    break\n",
    "                    \n",
    "                if not user_input:\n",
    "                    print(\"Please enter a name or type 'exit'.\")\n",
    "                    continue\n",
    "\n",
    "                # Split the input by commas and clean up extra spaces\n",
    "                search_names = [name.strip() for name in user_input.split(\",\") if name.strip()]\n",
    "                \n",
    "                # Combine multiple search names into a single regular expression\n",
    "                search_regex = \"|\".join(search_names)\n",
    "                result = df[df[player_col].str.contains(search_regex, case=False, na=False)]\n",
    "\n",
    "                if result.empty:\n",
    "                    print(f\"\\nCould not locate any footballers matching your search.\")\n",
    "                    \n",
    "                    # Fetch unique values for typo suggestions\n",
    "                    all_players = df[player_col].unique().tolist()\n",
    "                    for target in search_names:\n",
    "                        if not df[df[player_col].str.contains(target, case=False, na=False)].empty:\n",
    "                            continue\n",
    "                        suggestions = difflib.get_close_matches(target, all_players, n=2, cutoff=0.3)\n",
    "                        if suggestions:\n",
    "                            print(f\"\\nDid you mean for '{target}':\")\n",
    "                            for name in suggestions:\n",
    "                                print(f\" - {name}\")\n",
    "                else:\n",
    "                    # Filter out all requested exclusion columns safely if they exist\n",
    "                    columns_to_remove = [\"Matches\", \"Rk\", \"Age\", \"90s\", \"MP\", \"G+A\", \"G+A-PK\", \"Gls.1\", \"Ast.1\", \"G+A.1\", \"G-PK.1\"]\n",
    "                    clean_result = result.drop(columns=columns_to_remove, errors=\"ignore\")\n",
    "\n",
    "                    # Process text components and align columns accurately\n",
    "                    headers = [str(col) for col in clean_result.columns]\n",
    "                    raw_rows = clean_result.values.tolist()\n",
    "                    \n",
    "                    is_numeric_col = []\n",
    "                    for i in range(len(headers)):\n",
    "                        try:\n",
    "                            is_num = pd.api.types.is_numeric_dtype(clean_result.iloc[:, i])\n",
    "                            is_numeric_col.append(is_num)\n",
    "                        except Exception:\n",
    "                            is_numeric_col.append(False)\n",
    "\n",
    "                    formatted_rows = []\n",
    "                    for row in raw_rows:\n",
    "                        str_row = []\n",
    "                        for item in row:\n",
    "                            if pd.isna(item):\n",
    "                                str_row.append(\"\")\n",
    "                            elif isinstance(item, float) and item.is_integer():\n",
    "                                str_row.append(str(int(item)))\n",
    "                            else:\n",
    "                                str_row.append(str(item))\n",
    "                        formatted_rows.append(str_row)\n",
    "\n",
    "                    # Calculate sizing limits for grid building\n",
    "                    col_widths = []\n",
    "                    for i in range(len(headers)):\n",
    "                        max_w = len(headers[i])\n",
    "                        for row in formatted_rows:\n",
    "                            if len(row[i]) > max_w:\n",
    "                                max_w = len(row[i])\n",
    "                        col_widths.append(max_w)\n",
    "\n",
    "                    # --- Unicode Box-Drawing Borders ---\n",
    "                    top_border = \"┌\" + \"┬\".join([\"─\" * (w + 2) for w in col_widths]) + \"┐\"\n",
    "                    middle_border = \"├\" + \"┼\".join([\"─\" * (w + 2) for w in col_widths]) + \"┤\"\n",
    "                    bottom_border = \"└\" + \"┴\".join([\"─\" * (w + 2) for w in col_widths]) + \"┘\"\n",
    "\n",
    "                    # Output structured visual data grid\n",
    "                    print(\"\\n\" + top_border)\n",
    "                    header_cells = [f\" {headers[i].ljust(col_widths[i])} \" for i in range(len(headers))]\n",
    "                    print(\"│\" + \"│\".join(header_cells) + \"│\")\n",
    "                    print(middle_border)\n",
    "                    \n",
    "                    for idx, row in enumerate(formatted_rows):\n",
    "                        row_cells = []\n",
    "                        for i in range(len(row)):\n",
    "                            if i < len(is_numeric_col) and is_numeric_col[i]:\n",
    "                                row_cells.append(f\" {row[i].rjust(col_widths[i])} \")\n",
    "                            else:\n",
    "                                row_cells.append(f\" {row[i].ljust(col_widths[i])} \")\n",
    "                        print(\"│\" + \"│\".join(row_cells) + \"│\")\n",
    "                        \n",
    "                        # Add middle separators between multiple data rows, use bottom for the final row\n",
    "                        if idx < len(formatted_rows) - 1:\n",
    "                            print(middle_border)\n",
    "                    print(bottom_border)\n",
    "        else:\n",
    "            print(\"Notification: The Excel sheet appears to be empty.\")\n",
    "            input(\"\\nPress Enter to exit...\")\n",
    "            \n",
    "    except Exception:\n",
    "        print(\"\\nAn unexpected issue occurred while formatting the table layout.\")\n",
    "        input(\"\\nPress Enter to exit...\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
